name: CI

on:
  pull_request:
    branches:
      - main
      - master
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

env:
  NODE_VERSION: 24.12.0
  PNPM_VERSION: 10.26.0

jobs:
  linter:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/node-install
        with:
          pnpm-version: ${{ env.PNPM_VERSION }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@f382a98e582959e6aaac8e5f8b17b31749018780

      - name: Execute Biome
        run: pnpm biome:ci

      - name: Execute Prettier
        run: pnpm prettier:ci

      - name: Execute ESLint
        run: pnpm eslint:ci

      - name: Execute TypeCheck
        run: pnpm typecheck

      - name: Execute Build
        run: pnpm build
