name: CI

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  nuxt4-ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/nuxt4
    steps:
      - name: Checkout source code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/node-install

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@454fa0d884737805f48d7dc236c1761a0ac3cc13 # v2.6.0

      - name: Execute Biome
        run: pnpm biome:ci

      - name: Execute Prettier
        run: pnpm prettier:ci

      - name: Execute ESLint
        run: pnpm eslint:ci

      - name: Execute TypeCheck
        run: pnpm typecheck

      - name: Execute Vitest
        run: pnpm test:coverage

      - name: Execute Build
        run: pnpm build
  tanstack-ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/tanstack-start
    steps:
      - name: Checkout source code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/node-install

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@454fa0d884737805f48d7dc236c1761a0ac3cc13 # v2.6.0

      - name: Execute Biome
        run: pnpm biome:ci

      - name: Execute Prettier
        run: pnpm prettier:ci

      - name: Execute ESLint
        run: pnpm eslint:ci

      - name: Execute TypeCheck
        run: pnpm typecheck

      - name: Execute Build
        run: pnpm build

  tanstack-hono-ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/tanstack-start-x-hono
    steps:
      - name: Checkout source code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/node-install

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@454fa0d884737805f48d7dc236c1761a0ac3cc13 # v2.6.0

      - name: Execute ESLint
        run: pnpm eslint:ci

      - name: Execute Biome
        run: pnpm biome:ci

      - name: Execute Prettier
        run: pnpm prettier:ci

      - name: Execute TypeCheck
        run: pnpm typecheck
